[package]
name = "magitian_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.16.1"
uuid = { version = "1.2.2", features = ["v4"] }
